### ISSUE TITLE
Make announce URL option optional

### ISSUE THREAD

**Issue by isqua** [pobrn/mktorrent#12]
Many torrent clients can transfer files by setting peer IP and port and don’t need at announce URL.
Please, make this option optional.

**Comment by jdupl** [comment]
:+1:

**Comment by Rudde** [comment]
You can use the argument -a "" I know it's not perfect or what you asked for, but it works.

**Comment by isqua** [comment]
@Rudde, wow so hacky 😺

**Comment by Rudde** [comment]
Fixed in commit 77bc7d745bf53075989c804cc6434123201102dc
