### ISSUE TITLE
support for http seeds

### ISSUE THREAD

**Issue by eliasjonsson023** [pobrn/mktorrent#24]

**Comment by Calinou** [comment]
Isn't this supported already? The [wiki](https://github.com/Rudde/mktorrent/wiki) says:

> Can add web seed URLs.

**Comment by pobrn** [comment]
`mktorrent` supports specifying only [BEP 19 (WebSeed)](http://bittorrent.org/beps/bep_0019.html)-style HTTP/FTP seed URLs. There is also [BEP 17 (HTTP seeding)](http://bittorrent.org/beps/bep_0017.html), which is not yet supported.

@eliasjonsson023 could you clarify which one you meant?

**Comment by eliasjonsson023** [comment]
Thank you for asking. It is quite long ago, but I think I refered to BEP 19, Webseed. Now that mktorrent already supports that I rest my case.

**Comment by pobrn** [comment]
In that case I will close this issue, feel free to reopen if you deem it necessary.
