### ISSUE TITLE
README's URL is gone

### ISSUE THREAD

**Issue by mones** [pobrn/mktorrent#25]
The http://mktorrent.sourceforge.net/ URL in README gives a “Whoops, we can't find that page.”

Thanks!

**Comment by Rudde** [comment]
Expanded the Wiki page to include the info previously on the homepage. Might package version releases in the future.

**Comment by mones** [comment]
That's good, but the bad URL is still in README file, so the issue is not really resolved ;-)

**Comment by Rudde** [comment]
Ah, thanks, changed it to a link for the github wiki page.

**Comment by mones** [comment]
Thank you! :+1:
