### ISSUE TITLE
mktorrent.exe has stopped working

### ISSUE THREAD

**Issue by Simpuhl** [pobrn/mktorrent#3]
Screenshot: http://img177.imageshack.us/img177/486/mktorrenterror.png

Windows 7 64-bit.

I cannot figure out whats wrong, so annoying :(

**Comment by nikswap** [comment]
Could I ask you for the arguments given to mktorrent and the size of the file?

**Comment by pobrn** [comment]
The issue has been stale since 2011, thus I will close it, but if @Simpuhl you're still affected, please reopen it.

**Comment by Simpuhl** [comment]
> The issue has been stale since 2011, thus I will close it, but if @Simpuhl you're still affected, please reopen it.

LOL, this is old as hell but it's still happening. Nah jk. All good
